# Generated by Django 4.2.16 on 2026-05-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chassis",
                    models.CharField(
                        choices=[
                            ("W204", "W204 — C-Class (2007–2014)"),
                            ("W212", "W212 — E-Class (2009–2016)"),
                            ("W205", "W205 — C-Class (2014–2021)"),
                            ("W213", "W213 — E-Class (2016–present)"),
                            ("W176", "W176 — A-Class (2012–2018)"),
                            ("W246", "W246 — B-Class (2011–2018)"),
                            ("W166", "W166 — ML/GLE-Class (2011–2019)"),
                            ("W164", "W164 — ML-Class (2005–2011)"),
                            ("W221", "W221 — S-Class (2005–2013)"),
                            ("W222", "W222 — S-Class (2013–2020)"),
                            ("W251", "W251 — R-Class (2005–2017)"),
                            ("W463", "W463 — G-Class (1989–present)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Diagnostics", "In Diagnostics"),
                            ("Syncing", "Syncing"),
                            ("Ready", "Ready"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("report_filename", models.CharField(blank=True, max_length=255)),
                (
                    "report_file_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("report_mime_type", models.CharField(blank=True, max_length=100)),
                ("report_uploaded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "turnaround_days",
                    models.PositiveIntegerField(
                        help_text="Estimated turnaround time in days."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "compatible_chassis",
                    models.JSONField(
                        default=list,
                        help_text="List of compatible chassis codes, e.g. ['W204', 'W212'].",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Diagnostics", "In Diagnostics"),
                            ("Syncing", "Syncing"),
                            ("Ready", "Ready"),
                            ("Completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="services.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
